### ISSUE TITLE
Personal Donut checklist

### ISSUE THREAD

**Issue by CptWad** [CptWad/vgstation13#1]
This is my general changelog, this post will change over time as I complete shit. 

A checkbox means that something is worthy of playing. Generally all area, objects mobs and turfs are in place for the players. 

All floortiles subject to change, once I get shit settled ill go around and pretty everything

see lowest image for most updated map. Shit wont update the OP properly

Part one: The main donut station
- [ ] all base turfs, objects, mobs and areas down
- [ ] Pretty-fy the floortiles
- [ ] Test and double checked

Part two: The off station z-levels
- [ ] Research station
- [ ] Mining Station
- [ ] Vox traders
- [ ] Security Station
- [ ] Pretty
- [ ] Tested

Part Three: Central Command
- [ ] Central Command and shuttles to-from
- [ ] Antagonist Bases
- [ ] Holodeck, and other functional shit
- [ ] Metaclub

Part Four: Space exploration
- [ ] ?

**Current List: Part One**

- [ ] **Hallways**
- [x] \>Arrivals
- [x] \>>Arrivals Shuttle
- [ ] \>Fully worked Shuttles
- [x] \>Escape
- [x] \>North Hallway
- [x] \>West Hallway
- [ ] \>East Hallway
- [ ] \>South Hallway

- [ ] **Civilian**
- [x] \>Library
- [x] \>Service Department
- [x] \>Chapel
- [x] \>>Chapel Office
- [x] \>>Crematorium 
- [x] \>>And mourge
- [x] \>Dorms and Holodeck
- [x] \>>Locker Room
- [x] \>Fitness Rooms
- [x] \>Tool Storage(s)
- [ ] \>Janitor

- [x] **Cargo**

- [x] **Medbay**

- [x] **Research**

- [ ] **Engineering**
- [ ] \>Singlo
- [ ] \>Main
- [ ] \>Foyer
- [ ] \>Storages
- [ ] \>CE office
- [ ] \>Atmos
- [ ] \>>foyer
- [ ] \>Mommi
- [ ] \>SME
- [ ] \>Mechanics
- [ ] \>Pod Bay
- [ ] \>Solars
- [ ] \>Telecomms
- [x] \>Tech Storage

- [ ] **Fuctions**
- [ ] \>All disposal pipes connected and ready
- [ ] \>FULLY working pipe system
- [ ] \>FULLY power'd station

- [ ] **Sec**
- [ ] \>Courtroom
- [x] \>Detective
- [ ] \>Lobby
- [ ] \>Brig
- [ ] \>Warden
- [ ] \>Armory
- [ ] \>Evidence storage and interrogation
- [ ] \>HoS office
- [x] \>Lawyers

- [ ] **Command**
- [x] \>HoP
- [x] \>Captain
- [x] \>Bridge proper
- [x] \>Meeting room
- [ ] \>AI
- [ ] \>>Core
- [ ] \>>Upload
- [ ] \>>Misc
- [x] \>Teleporter

**Comment by CptWad** [comment]
![medbay](https://cloud.githubusercontent.com/assets/3959840/14506885/e5e0deb6-0174-11e6-9036-632436dccd6c.png)

**Comment by Probe1** [comment]
where the commits @

**Comment by CptWad** [comment]
no commits for a good long while

**Comment by CptWad** [comment]
ew no work in 24 hours
tomorrow im free time to tackle me some research department

**Comment by CptWad** [comment]
![donutcurrent](https://cloud.githubusercontent.com/assets/3959840/14698223/8b7e36f8-0741-11e6-8e6b-afa49e0a83e5.png)
go go go go go galo sengen

**Comment by Kammerjunk** [comment]
Stuff on medbay since no-one else is giving any feedback (might wanna put it in the thread if you haven't). This is all just my opinion.
:+1: Actual CMC in the lobby. Fuck you Duny
:+1: SmartFridge near entrance but not *at* the entrance so people storming in won't fuck with it
:+1: Borg charger already present
:+1: Virology moved way over there, fuck off virologists
:-1: Entrance could get kinda cramped. Maybe move the beds to just below storage, where virology access is?
:-1: There's quite a distance from cloning to cryo, but I can't really see any way to change that without radically changing the layout.
:question: Should the airlocks going into the sleeper and scanner area from the north be there?
:question: Morgue where?

**Comment by CptWad** [comment]
I guess I can move the beds

Distance from cloning to cryo is long yes but its not something that could be change, mind you originally the distance from cloning is far from medbay. Its an improvement but hell it works for our purposes. Meta has a similar cloning situation and they do fine

Airlocks there are funky but theres no airlocks next to cryo because of the above mentioned issue, having them their significantly increases walk time 

Chapel, neatly near detectives office and the mass driver, just like original Donut2.

**Comment by CptWad** [comment]
Progress chugging along, currently done with arrivals and its shuttle along with escape. I am working on cargo currently and pretty much just need to add a fuckton of items to have that off the docket.
After that I tackle the fuckhuge goon style chapel then onwards towards command, AI and sec.
But also I was checking around the center of the donut and realized how fucking LONG the travel time would be for a late join engineer and thought up a solution, how does this look?
![engineers](https://cloud.githubusercontent.com/assets/3959840/14766065/825cdb98-09b1-11e6-890d-f9f8789005d3.png)

**Comment by Probe1** [comment]
Take a 50% shot scaled out

**Comment by CptWad** [comment]
what like of the whole of the donut hallway?

**Comment by Probe1** [comment]
no dude just a 50% shot of the same area as the last pscreenshot

**Comment by CptWad** [comment]
wait can you zoom out in dreammaker ive never seen the option

**Comment by Probe1** [comment]
http://i.imgur.com/rdpD8Ln.jpg yeah right here.

**Comment by CptWad** [comment]
![singloth](https://cloud.githubusercontent.com/assets/3959840/14769075/6eebd2ea-0a05-11e6-9b92-fde46c7775e5.png)

**Comment by Probe1** [comment]
Yeah that EVA area works.

**Comment by CptWad** [comment]
nice
Cargo and disposals done
next up is chapel/mourge then the great march south.
I should clean up more of the checklist

**Comment by Probe1** [comment]
ja, das ist ordnung.

**Comment by Senaat1** [comment]
make cigars spawn in the law office

**Comment by CptWad** [comment]
not there yet but ill put them in a locker or something

**Comment by CptWad** [comment]
okay cigars are in
forgot a matchbox so if I dont remember just find a vending machine

**Comment by Hoshi-chan** [comment]
Wowee, what a gorgeous map. Great work so far.

My only criticisms would be that you should swap the positions of the chem fridge in chemistry and the rwindow/grille right next to it, so you can just dump pills into it from your position at the chem dispenser and chem master. Also, any hallway that is one tile wide is too narrow. Notably, that little spot in R&D where the person will ostensibly sit at the console with the machines behind them. That's going to be shove central, and it's going to be frustrating.

**Comment by CptWad** [comment]
alright duely noted
I should update that image

**Comment by CptWad** [comment]
![donutcurrent](https://cloud.githubusercontent.com/assets/3959840/14825190/b49a628c-0b8d-11e6-9cb6-754bef4fbffc.png)

**Comment by Probe1** [comment]
>that huge fucking farm
10/10

![9fpj7z72-1387485796](https://cloud.githubusercontent.com/assets/8550416/14825920/c95586cc-0ba9-11e6-877a-bfc66c78641d.jpg)

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/14825978/f42718de-0ba9-11e6-885b-a74d29982679.png)

needs a catwalk under the vent in space.

**Comment by CptWad** [comment]
done

**Comment by Probe1** [comment]
When this is closer to begin done I'll take a real hard look at everything.

**Comment by SquiddyMcNope** [comment]
Is it really that great of an idea to have telecommunications right there? Every other map places it in a fairly out of the way location, where as here it's surrounded by medbay, robitics, and various civilian areas. Having it in such a relatively central location would probably cause problems far more often, especially with the prospect of one bomb penetrating tcomms as well as taking out the medbay lobby and a high traffic hallway.

Looks pretty good overall, though.

**Comment by CptWad** [comment]
Well why not?
People should fuck with telecomms more often
Also they are motion sensor alarmed so at least the AI will know when someone is in there

**Comment by SquiddyMcNope** [comment]
Fair enough, as long as you're aware of it and it's not just been overlooked.

**Comment by CptWad** [comment]
reeeeee fucking byond 510 broke it
I am not smart enough to fix it send help
![fuck](https://cloud.githubusercontent.com/assets/3959840/14900345/f559f248-0d44-11e6-94f9-989fd9421221.png)
updating the code base did not fix it
when I opened it its just a 10x10 plating square

**Comment by CptWad** [comment]
well shit news, 510 killed it
I cant seem to recover it since 510 overwrote my file with a 16x16 square of plating
ill close this then keep my notes, I will try again when I get the motivation back

**Comment by CptWad** [comment]
yes im a madman

**Comment by Probe1** [comment]
I usually have 20+ commits on small mapping projects.  Every half hour or every "major" change.

I'm so sorry.

**Comment by Probe1** [comment]
rest in peace never 5get

**Comment by CptWad** [comment]
if this issue dissapears that would be a good sign
